import type { ArticleRecord } from "./types";

type LinkedPage = Omit<ArticleRecord, "id" | "status" | "featured" | "sort_order" | "published_at">;

function page(article: LinkedPage, sortOrder: number): ArticleRecord {
  return {
    ...article,
    id: `fallback-${article.slug}`,
    status: "published",
    featured: false,
    sort_order: 100 + sortOrder,
    published_at: "2026-08-14T08:00:00.000Z",
  };
}

export const linkedPages: ArticleRecord[] = [
  {
    slug: "the-interview-manual",
    title: "The Interview Manual",
    category_slug: "work",
    excerpt: "Everything you need before, during and after an interview — from preparation to the follow-up.",
    body: [
      "## Before the interview",
      "Start with the job description. Highlight the outcomes the employer wants, then prepare one example that proves you can deliver each important outcome. Research the organisation, its customers and its recent work. Your goal is not to memorise facts; it is to understand the problems the team is trying to solve.",
      "### Build your evidence bank",
      "Prepare five short stories from school, work, volunteering or personal projects. Use a simple structure: situation, responsibility, action and result. Put numbers on the result whenever you can.",
      "- A problem you solved\n- A time you worked with a difficult person\n- A mistake and what you changed\n- A moment you showed initiative\n- A result you are proud of",
      "### Practise the essentials",
      "Be ready to answer: Tell me about yourself, Why this role, Why this organisation, and What are you learning right now? Keep each answer clear and specific. Record yourself once; you will notice filler words and long detours immediately.",
      "## During the interview",
      "Listen to the whole question before answering. It is fine to pause for a few seconds. If a question is unclear, ask the interviewer to clarify it. Strong candidates do not rush; they make their thinking easy to follow.",
      "### Make the conversation useful",
      "Connect your examples to the role. Instead of saying you are hardworking, describe the deadline, the action you took and the outcome. If you do not know an answer, explain how you would find it rather than inventing one.",
      "### Ask better questions",
      "Use your questions to understand the work, not to perform interest. Ask what success looks like after 90 days, what the team is trying to improve, and what separates people who thrive in the role from those who struggle.",
      "## After the interview",
      "Send a brief thank-you message within 24 hours. Mention one useful point from the conversation and confirm your interest. If the employer gave a decision date, wait until that date passes before following up.",
      "### Your final checklist",
      "- Confirm the time, format and location\n- Test your connection, camera and audio\n- Carry copies of your CV and a notebook\n- Choose clean, comfortable clothes\n- Prepare five evidence stories and three questions\n- Send a short follow-up",
      "An interview is not a test of whether you are perfect. It is a structured conversation about whether your evidence, judgement and goals fit the work. Prepare the evidence and let the conversation do the rest.",
    ].join("\n\n"),
    image_url: "/editorial/interview.jpg",
    image_alt: "Ghanaian broadcaster Anita Erskine taking part in a television interview",
    read_time: "12 min read",
    author: "Today’s Manual",
  },
  {
    slug: "prepare-before-graduating",
    title: "What to Do Before You Graduate",
    category_slug: "skills",
    excerpt: "A practical final-year plan for leaving school with evidence, relationships and direction.",
    body: "## Build proof, not just potential\n\nChoose one useful skill and complete two small projects that show what you can do. A portfolio, case study or documented result gives an employer more to trust than a list of interests.\n\n## Get close to real work\n\nTalk to people doing roles you may want. Ask what their week looks like, which skills matter and what beginners misunderstand. Use internships, volunteering and student projects to practise working with deadlines and other people.\n\n## Leave with a system\n\nCreate a clear CV, a professional email address, a simple LinkedIn profile and a list of organisations to follow. Apply consistently, track every application and keep improving your evidence while you wait.",
    image_url: "/editorial/student.jpg",
    image_alt: "Young Ghanaian adults working together on laptops at a University of Ghana workshop",
    read_time: "5 min read",
    author: "Today’s Manual",
  },
  {
    slug: "start-your-career",
    title: "How to Actually Start Your Career",
    category_slug: "work",
    excerpt: "Your first role does not need to be perfect. It needs to teach you, expose you and move you forward.",
    body: "## Pick a direction for the next season\n\nYou do not need a lifelong plan. Choose a role family you can explore for six months, learn its basic tools and study the language employers use in job descriptions.\n\n## Make applications specific\n\nA strong application connects your evidence to the employer’s needs. Rewrite the top third of your CV for the role, include relevant projects and explain the result of your work.\n\n## Treat the search like work\n\nSet weekly targets for conversations, applications and portfolio improvements. Review what gets responses. Your first job is a starting platform, so prioritise learning, good management and real responsibility.",
    image_url: "/editorial/hero-laptop.jpg",
    image_alt: "Young man working on a laptop",
    read_time: "6 min read",
    author: "Today’s Manual",
  },
  {
    slug: "grow-faster-at-work",
    title: "How to Grow Faster at Work",
    category_slug: "work",
    excerpt: "Become easier to trust, easier to work with and more valuable on the problems that matter.",
    body: "## Learn what good means\n\nAsk your manager what success looks like in measurable terms. Confirm priorities, deadlines and the standard expected before you start.\n\n## Close loops\n\nGive short updates before people have to chase you. Raise risks early, bring possible solutions and document decisions. Reliability compounds because it earns you larger responsibilities.\n\n## Build leverage\n\nImprove one skill that makes your whole team faster: writing, analysis, sales, project management or automation. Keep a private record of outcomes so your next performance conversation is based on evidence.",
    image_url: "/editorial/office.jpg",
    image_alt: "Attendees preparing for a Young Entrepreneurs Summit in Ghana",
    read_time: "5 min read",
    author: "Today’s Manual",
  },
  {
    slug: "build-something-of-your-own",
    title: "Build Something of Your Own",
    category_slug: "opportunity",
    excerpt: "A grounded way to begin freelancing or business without waiting for the perfect idea.",
    body: "## Start with a painful problem\n\nLook for a specific group of people who already spend time or money solving a recurring problem. Speak to them before building. Their language will sharpen both the offer and the marketing.\n\n## Sell the smallest useful result\n\nDefine one customer, one problem, one promise and one price. Deliver manually at first. Early work should teach you what customers value before you invest in scale.\n\n## Protect the basics\n\nSeparate business money, record every expense, agree scope in writing and ask for a deposit. Consistency and trust are business advantages long before you have a large audience.",
    image_url: "/editorial/buildings.jpg",
    image_alt: "People walking past small businesses on a busy market street in Accra",
    read_time: "6 min read",
    author: "Today’s Manual",
  },
  {
    slug: "find-your-next-step",
    title: "How to Find Your Next Step When You Feel Lost",
    category_slug: "life",
    excerpt: "You do not need to solve your whole life today. You need a smaller, testable next move.",
    body: "## Reduce the size of the question\n\nReplace “What should I do with my life?” with “What can I test in the next two weeks?” Clarity usually follows action rather than arriving before it.\n\n## Use three lists\n\nWrite what gives you energy, what you can already do and which problems people need solved. Look for small overlaps, then speak to someone working in each possible direction.\n\n## Run a low-risk experiment\n\nTake a short course, shadow someone, volunteer or complete a project. At the end, decide whether to continue, change direction or stop. A useful experiment produces evidence even when the answer is no.",
    image_url: "/editorial/desk.jpg",
    image_alt: "Ghanaian students learning together with a laptop in a classroom",
    read_time: "5 min read",
    author: "Today’s Manual",
  },
  {
    slug: "voices",
    title: "Voices",
    category_slug: "life",
    excerpt: "Honest stories from young Africans building careers, businesses and lives in changing times.",
    body: "## Real experience is useful knowledge\n\nVoices is where people tell the part of the story that polished profiles leave out: the uncertainty, the wrong turns, the money decisions and the quiet work behind progress.\n\n## Share your story\n\nWe welcome thoughtful first-person accounts with a clear lesson for other readers. Tell us what happened, what changed your thinking and what someone in the same position can do next. Use the Contact page to introduce yourself and your idea.",
    image_url: "/editorial/voice.jpg",
    image_alt: "A young Ghanaian man speaking during a University of Ghana workshop",
    read_time: "3 min read",
    author: "Today’s Manual",
  },
  {
    slug: "about-us",
    title: "About Today’s Manual",
    category_slug: "life",
    excerpt: "Practical knowledge, honest conversations and useful direction for modern African life.",
    body: "## A guide for the generation building tomorrow\n\nToday’s Manual is an independent publication for young Africans navigating work, money, skills, life and opportunity. We turn complicated questions into clear, useful guidance.\n\n## What we publish\n\nOur work includes practical manuals, explainers, interviews and first-person stories. We care about context, honest trade-offs and actions a reader can take today.\n\n## Made in Africa\n\nWe begin with African realities and remain open to useful ideas from everywhere. Our aim is simple: help readers make better decisions and build lives with more agency.",
    image_url: "/editorial/life.jpg",
    image_alt: "A Ghanaian environmental initiative team gathered around a work table",
    read_time: "3 min read",
    author: "Today’s Manual",
  },
  {
    slug: "our-mission",
    title: "Our Mission",
    category_slug: "life",
    excerpt: "To make practical knowledge easier to find, understand and use across Africa.",
    body: "## Useful knowledge should be accessible\n\nToo much important guidance is vague, imported without context or locked behind networks. Today’s Manual exists to close that gap.\n\n## Our promise\n\nWe will explain the real options, name the trade-offs and give readers a useful next step. We will keep learning from the people living these questions every day.",
    image_url: "/editorial/opportunity.jpg",
    image_alt: "A diverse group of young Ghanaian adults outside the University of Ghana",
    read_time: "2 min read",
    author: "Today’s Manual",
  },
  {
    slug: "editorial-principles",
    title: "Editorial Principles",
    category_slug: "skills",
    excerpt: "The standards we use to make Today’s Manual accurate, useful and worthy of trust.",
    body: "## Accuracy before speed\n\nWe verify factual claims, distinguish reporting from opinion and correct material errors clearly.\n\n## Usefulness before noise\n\nEvery story should help the reader understand a decision, see an opportunity or take a practical next step.\n\n## Context matters\n\nWe avoid pretending one answer works for everyone. We name uncertainty, costs and relevant local conditions. Commercial relationships do not buy editorial conclusions, and sponsored work will be labelled.",
    image_url: "/editorial/skills.jpg",
    image_alt: "Young Ghanaian women participating in a laptop-based technology workshop",
    read_time: "3 min read",
    author: "Today’s Manual",
  },
  {
    slug: "write-for-us",
    title: "Write for Us",
    category_slug: "opportunity",
    excerpt: "Pitch practical, original stories that help young Africans make better decisions.",
    body: "## What we want\n\nWe look for reported guides, sharp explainers and honest first-person stories about work, money, skills, life and opportunity. A strong pitch has a clear reader, a specific question and evidence you can access.\n\n## How to pitch\n\nSend a short summary, the intended reader, why the story matters now, your reporting plan and links to previous work. Do not send a completed draft unless requested. Use the Contact page and choose Writing or contribution as the subject.",
    image_url: "/editorial/desk.jpg",
    image_alt: "Ghanaian students learning together with a laptop in a classroom",
    read_time: "3 min read",
    author: "Today’s Manual",
  },
  {
    slug: "contributors",
    title: "Contributors",
    category_slug: "life",
    excerpt: "The writers, editors, photographers and specialists helping build Today’s Manual.",
    body: "## Built with people who know the work\n\nToday’s Manual collaborates with writers, practitioners and subject specialists across Africa. Contributors are selected for relevant experience, clear thinking and respect for the reader.\n\n## Join the network\n\nWe are building our contributor directory. If you have a useful perspective or area of expertise, introduce yourself through the Contact page and include links to your work.",
    image_url: "/editorial/voice.jpg",
    image_alt: "A young Ghanaian man speaking during a University of Ghana workshop",
    read_time: "2 min read",
    author: "Today’s Manual",
  },
  {
    slug: "the-manual",
    title: "The Manual",
    category_slug: "skills",
    excerpt: "Deep, practical guides for the decisions that shape work, money and life.",
    body: "## Built to be used\n\nManuals are definitive guides that organise a difficult topic into preparation, action and follow-through. They include checklists, examples and questions you can return to.\n\n## Start here\n\nBegin with The Interview Manual, then explore the Work, Money, Skills, Life and Opportunity sections for guides matched to your current challenge.",
    image_url: "/editorial/interview.jpg",
    image_alt: "Ghanaian broadcaster Anita Erskine taking part in a television interview",
    read_time: "3 min read",
    author: "Today’s Manual",
  },
  {
    slug: "opportunities",
    title: "Opportunities",
    category_slug: "opportunity",
    excerpt: "Jobs, scholarships, fellowships, grants and programmes worth your attention.",
    body: "## Opportunity with context\n\nWe look beyond the headline to explain who an opportunity is for, what it requires, the deadline and the cost of applying.\n\n## Check before you apply\n\nAlways confirm details on the organiser’s official website. Never pay an unofficial agent for access to a scholarship or job. New opportunity roundups will appear in the Opportunity Manual.",
    image_url: "/editorial/opportunity.jpg",
    image_alt: "A diverse group of young Ghanaian adults outside the University of Ghana",
    read_time: "3 min read",
    author: "Today’s Manual",
  },
  {
    slug: "podcast",
    title: "The Today’s Manual Podcast",
    category_slug: "life",
    excerpt: "Practical conversations about the decisions nobody teaches clearly.",
    body: "## Conversations you can use\n\nThe Today’s Manual Podcast is in development. It will bring together practitioners and honest personal stories across work, money, skills, life and opportunity.\n\nUse the Contact page to suggest a guest, a question or a partnership.",
    image_url: "/editorial/voice.jpg",
    image_alt: "A young Ghanaian man speaking during a University of Ghana workshop",
    read_time: "2 min read",
    author: "Today’s Manual",
  },
  {
    slug: "videos",
    title: "Today’s Manual Videos",
    category_slug: "skills",
    excerpt: "Clear visual explainers and practical conversations, made for the way people learn now.",
    body: "## Watch, understand, act\n\nOur video library is in development. New explainers and interviews will turn the most useful parts of Today’s Manual into concise visual lessons.\n\nFollow our official social channels for the first releases and use the Contact page to suggest a subject.",
    image_url: "/editorial/interview.jpg",
    image_alt: "Ghanaian broadcaster Anita Erskine taking part in a television interview",
    read_time: "2 min read",
    author: "Today’s Manual",
  },
  {
    slug: "advertise",
    title: "Advertise with Today’s Manual",
    category_slug: "opportunity",
    excerpt: "Reach an ambitious audience with useful, clearly labelled commercial work.",
    body: "## Work that respects the reader\n\nWe consider advertising and sponsorship from organisations whose products, services and opportunities are relevant to our audience. Paid placements are clearly labelled and do not determine independent editorial conclusions.\n\n## Start a conversation\n\nUse the Contact page and choose Advertising or commercial enquiry. Include your organisation, objective, timing and intended audience.",
    image_url: "/editorial/buildings.jpg",
    image_alt: "People walking past small businesses on a busy market street in Accra",
    read_time: "2 min read",
    author: "Today’s Manual",
  },
  {
    slug: "partner-with-us",
    title: "Partner with Us",
    category_slug: "opportunity",
    excerpt: "Build useful programmes, research and stories for the generation shaping Africa’s future.",
    body: "## What partnership can look like\n\nWe are open to editorial series, research, events, learning resources and distribution partnerships that create clear value for readers.\n\n## Tell us what you want to build\n\nUse the Contact page with your organisation, the problem you want to solve, the proposed contribution from each partner and the outcome you want to create.",
    image_url: "/editorial/work.jpg",
    image_alt: "Ghanaian professionals and students collaborating around laptops at a workshop",
    read_time: "2 min read",
    author: "Today’s Manual",
  },
  {
    slug: "privacy-policy",
    title: "Privacy Policy",
    category_slug: "life",
    excerpt: "How Today’s Manual collects, uses and protects information you choose to share.",
    body: "## Information we collect\n\nWhen you subscribe or contact us, we collect the information you submit, such as your email address, name, subject and message. Our hosting and security providers may also process basic technical logs needed to operate and protect the website.\n\n## How we use it\n\nWe use submitted information to deliver requested updates, answer enquiries, operate the publication and prevent abuse. We do not sell personal information. We share it only with service providers needed to run these functions or where required by law.\n\n## Your choices\n\nYou may unsubscribe using the link in an email or contact us to ask about correction or deletion of information you submitted. Reasonable records may be retained for security, legal or operational purposes.\n\n## Contact\n\nQuestions about this policy can be sent through the Contact page. This policy was last updated on 14 August 2026.",
    image_url: "/editorial/life.jpg",
    image_alt: "A Ghanaian environmental initiative team gathered around a work table",
    read_time: "4 min read",
    author: "Today’s Manual",
  },
  {
    slug: "terms-of-use",
    title: "Terms of Use",
    category_slug: "life",
    excerpt: "The basic terms for accessing and using Today’s Manual.",
    body: "## Using the publication\n\nToday’s Manual provides general educational and editorial information. It is not personal legal, medical or financial advice. You remain responsible for decisions made using the information.\n\n## Our work\n\nUnless a page says otherwise, Today’s Manual owns its original text, branding and design. You may share links and short attributed excerpts. Republishing substantial material requires written permission. Third-party images and materials remain subject to their stated licences.\n\n## Availability and conduct\n\nWe may update, correct or remove material and cannot guarantee uninterrupted access. Do not misuse the website, attempt unauthorised access or submit unlawful, abusive or deceptive content.\n\n## Contact\n\nQuestions about these terms can be sent through the Contact page. These terms were last updated on 14 August 2026.",
    image_url: "/editorial/life.jpg",
    image_alt: "A Ghanaian environmental initiative team gathered around a work table",
    read_time: "4 min read",
    author: "Today’s Manual",
  },
].map(page);
